### ISSUE TITLE
Compressed image is bigger than the original

### ISSUE THREAD

**Issue by ospfranco** [kelvin13/swift-png#28]
Once again, thanks for the library! This issue is related to my [previous one](https://github.com/kelvin13/swift-png/issues/27). I'm basically trying to compress/optimize for file size as much as I can, yet the image I get from the .compress (with level 13) call is bigger than the original one by a huge margin, I imagine because extra bits are being used/padded per pixel.

Any recommendation to aggressively reduce file size?

<img width="543" alt="Screenshot 000807" src="https://user-images.githubusercontent.com/1634213/181876119-e62db209-b95f-4308-898a-a2c978012195.png">

**Comment by kelvin13** [comment]
hi, can you share the smaller image?

**Comment by ospfranco** [comment]
Thanks for replying, I gave up on this idea. The image was just a screenshot I took from my desktop using `cmd + shift + 4` nothing special about it. Feel free to close the ticket, otherwise just leave it open as future reference for people trying to reduce file size.

**Comment by kelvin13** [comment]
okay, i'm still very interested in how the first image is half the size, so if you could attach a copy of it, that would be greatly appreciated :)

**Comment by ospfranco** [comment]
Sorry, I already deleted the file I was using for testing.

**Comment by ospfranco** [comment]
I can give you this image:

![Screenshot 000814_1659371004 521134_optimized](https://user-images.githubusercontent.com/1634213/182197228-58813046-8b86-46ea-9b45-6be583e99a64.png)

I ran it through [pngquant](https://pngquant.org) which was the library I was looking to replace with swift-png. The image size is as small as it gets (tinyPNG produces an even smaller file, but they are closed source). I would have liked for swift-png to have produced such a small file size, or at least close to it, even if it required tweaking.

**Comment by ospfranco** [comment]
This is the original screenshot taken with cleanShotX

<img width="537" alt="Screenshot 000814" src="https://user-images.githubusercontent.com/1634213/182197866-6dacb02e-5506-4117-83ec-82e10d71d6d4.png">

**Comment by kelvin13** [comment]
ah, that explains it! `pngquant` is a *lossy* image compressor, `swift-png` is a *lossless* image codec. lossy algorithms will of course produce smaller output files, but at the expense of information loss and ability to re-encode.

**Comment by ospfranco** [comment]
Makes sense 👍 thanks!
