### ISSUE TITLE
utils/benchmark cannot compile baseline

### ISSUE THREAD

**Issue by valeriyvan** [kelvin13/swift-png#41]
```
utils/benchmark    
clang -Wall -Wpedantic -lpng benchmarks/decompression/baseline/main.c -o benchmarks/decompression/baseline/main
benchmarks/decompression/baseline/main.c:6:10: fatal error: 'png.h' file not found
#include <png.h>
         ^~~~~~~
1 error generated.
```

**Comment by kelvin13** [comment]
this is expected, the benchmark compares against `libpng`, so you must have `libpng` installed to run the benchmark

**Comment by wadetregaskis** [comment]
I have libpng installed (via `brew install libpng`) but this problem persists.  It appears it's not looking for the library in the right place (/opt/homebrew, the standard installation location).
